# AWS buildspec version (not version of this buildspec)
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      golang: 1.14
  pre_build:
    commands:
      - npm run testwasm
  build:
    commands:
      - npm install
      - cd src/go && GOOS=js && GOARCH=wasm && go build -o  ../../public/wasm/main.wasm && cd ../..
      - npm run build
artifacts:
  files:
    - server.js
    - build/**/*

eb_codebuild_settings:
  CodeBuildServiceRole: GoWithGo
  ComputeType: BUILD_GENERAL1_SMALL
  Image: aws/codebuild/amazonlinux2-aarch64-standard:2.0